# oxh-hyprland-dotfiles by occhi

general {
    lock_cmd = none
    before_sleep_cmd = hyprctl dispatch dpms off
    after_sleep_cmd  = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

listener {
    timeout  = 300
    on-timeout = bash -c 'playerctl status 2>/dev/null | grep -q Playing || hyprctl dispatch dpms off'
    on-resume  = hyprctl dispatch dpms on
}
