# ─────────────────────────────────────────
# hyprland-ricing by occhi
# ~/.config/hypr/hyprpaper.conf
# ─────────────────────────────────────────
# Adapted for: laptop (panel interno)
# Verificá el nombre exacto con: hyprctl monitors
# En notebooks suele ser eDP-1. Si no funciona probá LVDS-1.

preload   = ~/wallpapers/wallpaper.jpg
wallpaper = eDP-1, ~/wallpapers/wallpaper.jpg
splash    = false
